### ISSUE TITLE
Frontend of the project or Deployment of model 

### ISSUE THREAD

**Issue by akrish4** [SanjayMarreddi/ML_Internship_Technocolabs#12]
I would like to contribute to this project in frontend or deployment of model to heruku using flask?
let me know can i contribute it ? I am part of DevScript winter of code (dwoc)

**Comment by akrish4** [comment]
@SanjayMarreddi

**Comment by SanjayMarreddi** [comment]
@akrish4  Sure, You can contribute. Go ahead !

One Small thing, There are already Issues made for both `Deployment of Model` (#3) and `Making Frontend Attractive`(#4).

Just Comment there, I will assign you those Two Issues. Kindly Close this Issue.

Good Luck !!

**Comment by akrish4** [comment]
yeah okay @SanjayMarreddi , i would like to work on these issues , thank you.
kindly assign me with it.
