### ISSUE TITLE
CODE OF CONDUCT file 

### ISSUE THREAD

**Issue by akrish4** [SanjayMarreddi/ML_Internship_Technocolabs#15]
Hi @SanjayMarreddi  
I found that this project repository is not having a `code of conduct` file in this repository , 
kindly assign me this issue and I would like to contribute a well formatted code of conduct file  as you know code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum

**Comment by SanjayMarreddi** [comment]
@akrish4 Thanks for suggesting. But one of our friend already made `CODE OF CONDUCT` and made a PR(#13 ) which is currently under Review. Kindly Close this Issue and Open other Issue for new Idea or work on other existing Issues.
Good Luck !

**Comment by akrish4** [comment]
ok 
thank you @SanjayMarreddi
