### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [SanjayMarreddi/ML_Internship_Technocolabs#19]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by muthuannamalai12** [comment]
> I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> For reference, check out: https://github.com/apps/welcome
> 
> If you feel this is a great idea!
> Please assign it to me.

I would love to work on this issue as a part of DWOC.Kindly assign it to me

**Comment by SanjayMarreddi** [comment]
@muthuannamalai12 Done, Go Ahead.

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it @SanjayMarreddi

**Comment by muthuannamalai12** [comment]
@SanjayMarreddi Can you please add the level label of my PR here?

**Comment by SanjayMarreddi** [comment]
@muthuannamalai12  This PR is not merged. Instead you made a new PR (#20) which was merged & Level Label is added too.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12  This PR is not merged. Instead you made a new PR (#20) which was merged & Level Label is added too.

Ok Thank you. Sorry for inconvenience
