### ISSUE TITLE
ADD ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by tharunc** [SanjayMarreddi/ML_Internship_Technocolabs#21]
Hello there,
           I would like to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal. Kindly assign me this issue as a part of **DWOC**.
THANK YOU

**Comment by SanjayMarreddi** [comment]
@tharunc Assigned.  You can start working, Good Luck !


Also @muthuannamalai12 Can u look at this point why didn't the Welcome bot activate here ?

**Comment by muthuannamalai12** [comment]
> @tharunc Assigned. You can start working, Good Luck !
> 
> Also @muthuannamalai12 Can u look at this point why didn't the Welcome bot activate here ?
@SanjayMarreddi Welcome bot is working when I have tested. Does this repository has a welcome bot installed. Even If I do it in my forked repo it has to done on your original repo also. It can be downloaded from here https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
I have checked it now also it is working for me @SanjayMarreddi 
![bot 5](https://user-images.githubusercontent.com/64524822/104114926-d3fbe080-532f-11eb-8452-7ff22ae359bc.png)

**Comment by muthuannamalai12** [comment]
I have checked it now. It is working @SanjayMarreddi  
![bot 5](https://user-images.githubusercontent.com/64524822/104114941-0279bb80-5330-11eb-8b0c-f95fb3140523.png)
