### ISSUE TITLE
PR TEMPLATE

### ISSUE THREAD

**Issue by muthuannamalai12** [SanjayMarreddi/ML_Internship_Technocolabs#32]
## 🚀 Feature
I can add a pr template , which will have few checklists and options like uploading screenshots and describing about the pr etc , which will give better understanding of pr for the maintainer
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model/blob/master/CODE_OF_CONDUCT.md)?
Yes
(Write your answer here.)

## Motivation
Self Motivation
(Please outline the motivation for the proposal.)

## Pitch
This is a great feature like issue template in this project , this will give a better idea about the pr and also make the work easy
(Please explain why this feature should be implemented and how it would be used.)

**Comment by SanjayMarreddi** [comment]
@muthuannamalai12 Assigned to you. You can start working.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 Assigned to you. You can start working
Kindly add DWOC tag and level tag @SanjayMarreddi. I forget to add in the issue I have created.

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
