### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by tharunc** [SanjayMarreddi/ML_Internship_Technocolabs#48]
I would like to add Contributing.md with the following features.

1.We can add Github documentation links for
i). Getting started with Git and GitHub
ii). Forking a Repo
iiI). Cloning a Repo
iv). How to create a Pull Request
2.Also, we can give the links for git installation
3.We can also add Style Guides for Git Commit Messages
These things will help people new to opensource understand clearly on how to create an issue and how to create a PR.

I would like to add this in a folder and incorporate it in the readme.

**Comment by SanjayMarreddi** [comment]
@tharunc Go ahead & do it. Good Luck !

**Comment by tharunc** [comment]
Please add **DWOC** TAG.
