### ISSUE TITLE
Auto Updating Contributors table 

### ISSUE THREAD

**Issue by Swastik1710** [SanjayMarreddi/ML_Internship_Technocolabs#49]
## 🐛 Bug Report

As of now the Contributors table is not up to date. 
Moreover, it is hard coded so needs to be updated manually each and every time. 
I wanna add a Contributors table which would update automatically. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by Swastik1710** [comment]
Kindly assign me this issue so that I can start working on it.

**Comment by SanjayMarreddi** [comment]
@Swastik1710 Assigned, You can start working on it. Good Luck !

Btw, Are you trying to do it using a bot. If so, refer this (#30)

**Comment by Swastik1710** [comment]
It can be done using a bot but I would be adding a dynamic link to the readme file which displays the Contributors image. 
This makes it very simple compared to the bot method which causes merge conflicts and other unknown bugs.

**Comment by Swastik1710** [comment]
![1](https://user-images.githubusercontent.com/71871571/108215774-b5231200-7157-11eb-8087-bf055fa96744.PNG)
@SanjayMarreddi 
It will look like this.
Let me know your views so that I can start working on this.

**Comment by SanjayMarreddi** [comment]
@Swastik1710 Okay, This is also fine!

**Comment by Swastik1710** [comment]
Hey @SanjayMarreddi , I've made a PR regarding this issue.
Do check it out and please add the DWOC and Level labels to the PR .
