### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by Vrushti24** [SanjayMarreddi/ML_Internship_Technocolabs#51]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model/blob/master/CODE_OF_CONDUCT.md)?
We can add a beautiful logo in your project to look it more attractive .

**Comment by Vrushti24** [comment]
Please assign me this @SanjayMarreddi

**Comment by Vrushti24** [comment]
Can u add labels level and DWOC and u can tell me some points if u want to @SanjayMarreddi

**Comment by SanjayMarreddi** [comment]
@Vrushti24 Done, You can start working. Good Luck!
