### ISSUE TITLE
Can i get the Train and Test Data used to  emotions Facial Recognition Model

### ISSUE THREAD

**Issue by culeforlife10** [SanjayMarreddi/ML_Internship_Technocolabs#64]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model/blob/master/CODE_OF_CONDUCT.md)?

(Write your answer here.)
Train and Test Data Used to Train Enotions Recognition model

**Comment by SanjayMarreddi** [comment]
Hi, 
We have used a slightly modified version of this dataset. https://www.kaggle.com/msambare/fer2013
Good Luck!
